### ISSUE TITLE
MapQuest Open tiles need a different URL under https

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-spatial#101]
http://developer.mapquest.com/en_GB/web/products/forums/-/message_boards/message/361212;jsessionid=Ywinq8QmUJjpW1dX14vV.0

**Comment by mattfullerton** [comment]
This would be the workaround (development/production.ini):
ckanext.spatial.common_map.type = custom
ckanext.spatial.common_map.custom.url = //otile{s}-s.mqcdn.com/tiles/1.0.0/osm/{z}/{x}/{y}.png
ckanext.spatial.common_map.attribution = Map data &copy; OpenStreetMap contributors, Tiles Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="//developer.mapquest.com/content/osm/mq_logo.png">
ckanext.spatial.common_map.subdomains = 1234
