### ISSUE TITLE
Parameter for view for which WMS layers to show by default

### ISSUE THREAD

**Issue by mattfullerton** [ckan/ckanext-spatial#106]
Currently, if multiple layers are present, only the first is shown. I would like to be able to put in the view properties which layer(s) should be shown as a simple comma separated list. If someone points me in the right direction on where to start on this, I could work on it.

**Comment by amercader** [comment]
Hi @mattfullerton, I'm literally finishing work this week to remove the WMS viewer in spatial in favour of the brand new one at https://github.com/ckan/ckanext-geoview (which is serveral orders of magnitude better thanks to @pduchesne) and announce it.

What you suggest seems entirely sensible, let's discuss it on a new issue over the new repo.

**Comment by mattfullerton** [comment]
Ah as usual I'm one step behind ;-)

**Comment by mattfullerton** [comment]
@amercader Is there a particular ckan/branch you're testing against? My quick install of the plugin yields an error of trying to assign an item to a string. I can also just wait till you're finished :)

**Comment by amercader** [comment]
sorry about that @mattfullerton, can you paste me the stacktrace?

**Comment by amercader** [comment]
@mattfullerton got it https://github.com/ckan/ckanext-geoview/issues/6
