### ISSUE TITLE
require requests==2.7.0

### ISSUE THREAD

**Issue by florianm** [ckan/ckanext-spatial#110]
Could the required version of requests be updated to the currently latest 2.7.0? I've tried that on my end without running in to any troubles. From reading request's change logs, no breaking changes or backwards-incompatibilities have been introduced since 1.1.0.
Happy to submit PR if appropriate.

**Comment by florianm** [comment]
as discussed with @amercader at ckan/ckan-service-provider/pull/30, ckan pins requests==2.3.0, so I'll suggest either letting requests float here, as ckanext-spatial will almost always come with ckan. This is not urgent however.

**Comment by davidread** [comment]
This was fixed a few weeks ago to allow 2.7.0: pip-requirements.txt has ```requests>=1.1.0``` now.
