### ISSUE TITLE
how to filter the resultset

### ISSUE THREAD

**Issue by hknochi** [ckan/ckanext-spatial#111]
how the resultset can be filtered with given/existing capabilities

fetched capabilities:

```
<ows:Parameter name="CONSTRAINTLANGUAGE">
<ows:Value>Filter</ows:Value>
</ows:Parameter>
```

so the cql can't be used 

are there any suggestions how to add a filter or contstraints

**Comment by davidread** [comment]
I think this relates to the legacy csw server that we've just removed from ckanext-spatial, so closing. If that's not correct, feel free to reopen with fuller info.
