### ISSUE TITLE
Solr Spatial Field and Solr 5

### ISSUE THREAD

**Issue by FabiApfelkern** [ckan/ckanext-spatial#114]
It is necessary to tweak the code a little bit to get the Solr Spatial Field running with Solr 5. [1] Is it possible to incorporate this behavior into the code. E.g. a configuration value. 

[1] https://gist.github.com/u10313335/5649488bc3a4037e1357

**Comment by amercader** [comment]
The suggested code on the gist also works on Solr 4 so I think it's worth just replacing the existing one. Happy to review and merge a PR

**Comment by MrkGrgsn** [comment]
Hi @amercader. Any chance of having the PR reviewed? It would be useful to have this in master.
