### ISSUE TITLE
Using Spatial Search Widget does not give any result

### ISSUE THREAD

**Issue by bunnis** [ckan/ckanext-spatial#120]
When defining a search area for Spatial Search Widget and trying to search datasets inside it gives zero results. 
ckan 2.4.1
ckanext-spatial as of 16 october

any idea why?

**Comment by bunnis** [comment]
solved by adding solr schema lines and reindexing

For future use add reindexing command to documentation.

sudo nano /home/bunny/ckan/lib/default/src/ckan/ckan/config/solr/schema.xml

<fields>
    
    <field name="bbox_area" type="float" indexed="true" stored="true" />
    <field name="maxx" type="float" indexed="true" stored="true" />
    <field name="maxy" type="float" indexed="true" stored="true" />
    <field name="minx" type="float" indexed="true" stored="true" />
    <field name="miny" type="float" indexed="true" stored="true" />
</fields>
paster --plugin=ckan search-index rebuild --config=/etc/ckan/default/development.ini

**Comment by davidread** [comment]
I added a couple of lines of docs about this. Can you check this makes sense: https://github.com/ckan/ckanext-spatial/pull/123

**Comment by bunnis** [comment]
I made my own forsk and commit. check https://github.com/ckan/ckanext-spatial/pull/122 . Yours is fine too

**Comment by davidread** [comment]
Many thanks for contributing the problem and solution. Sorry I didn't spot yourPR first, but pleased the docs are improved anyway.
