### ISSUE TITLE
enabling debug mode in ckan 2.4.1 resutls in spatial errors

### ISSUE THREAD

**Issue by bunnis** [ckan/ckanext-spatial#121]
Followed the guide to install spatial. It works, but if you enable debug mode in ckan this happens

AttributeError: 'module' object has no attribute 'css/main.debug.css'
CKAN_DEBUG_INFO	[{'template_path': '/home/bunny/ckan/lib/default/src/ckan/ckan/templates/package/search.html', 'vars': {'session': {'_accessed_time': 1445346426.288689, '_creation_time': 1444382660.514316}, 'c': <pylons.util.AttribSafeContextObj at 0x7f5a2e322990 action=u'search', author=u'deimos', controller=u'package', drill_down_url=<function drill_down_url at 0x7f5a27cd5aa0>, environ={'AUTH_TYPE': 'cookie', 'routes.route': <routes.route.Route ...dch'}, facet_titles=OrderedDict([('organization', u'Organizations'), ('groups', ...s')]), facets={'organization': {'esa-sentinel-data-hub': 1135}, 'license_i...133}}, fields=[], fields_grouped={}, groups_authz=[], groups_available=[], is_sysadmin=True, language='en', licences=[('', ''), (u'License not specified', u'notspecified'), (u'O...ed')], licenses=[('', ''), (u'License not specified', u'notspecified'), (u'O...ed')], page=Page: Collection type: <type 'list'> (Current) page: 1 Fi... 57 , pylons=<pylons.util.PylonsContext object ...er', 'userobj']}]

**Comment by davidread** [comment]
This is covered here: http://stackoverflow.com/questions/13480800/ckan-development-install-issue-attributeerror-module-object-has-no-attribute
