### ISSUE TITLE
Spatial search

### ISSUE THREAD

**Issue by kapucko** [ckan/ckanext-spatial#130]
Hello,

I would like to modify my ckanext-spatial fork to search for smth like contains (if package extent is contained by search box) instead of intersection between them. Is it doable?
I think that I need to change the line in ckanext/spatial/lib/__init__.py :

extents = Session.query(PackageExtent) \
              .filter(PackageExtent.package_id==Package.id) \
              .filter(PackageExtent.the_geom.intersects(input_geometry)) \
              .filter(Package.state==u'active')

Could you help me please?

**Comment by tomkralidis** [comment]
This question is better asked on the ckan-dev [mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev).
