### ISSUE TITLE
Spatial Field On Row Data

### ISSUE THREAD

**Issue by conorw** [ckan/ckanext-spatial#133]
Hi,
Love this extension but I have a quick question about spatial features at the row level.

From my understanding the current spatial features allow you to set a map extent for the dataset as a whole and then search for datasets within a specified extent. 
Is it possible to do the same for row data? I.e. specify a postgis geom column for each row of data which can be searched from the API?

Apologies if this is an obvious question or this is not the correct place to ask it.

Thanks,

Conor

**Comment by davidread** [comment]
Hi Conor, ckan-dev is the best place to ask questions.
