### ISSUE TITLE
remove legacy CSW server implementation

### ISSUE THREAD

**Issue by tomkralidis** [ckan/ckanext-spatial#134]
cc @amercader @davidread 

It has been over 2 years since pycsw has been the CKAN CSW server implementation.

What do folks think about removing the [legacy/deprecated](http://docs.ckan.org/projects/ckanext-spatial/en/latest/csw.html#legacy-plugins-and-libraries) CSW server implementation?

If folks agree I will issue a PR.

**Comment by amercader** [comment]
+1
