### ISSUE TITLE
Issue Loading plugin

### ISSUE THREAD

**Issue by barry1955** [ckan/ckanext-spatial#153]
Hi,
I am trying to use the ckan-spatial plugin

I have add the following line to my ini file:

`ckan.plugins = stats text_view image_view recline_view spatial_metadata spatial_query resource_proxy geojson_view geo_view dataset_extent_map wms_preview`

I get a Server 500 errot and the log file sentry says:

`PluginNotFoundException: dataset_extent_map`

I had the map search working.

Where is the best place to look to see what is happening?

Stay well
Barry

**Comment by amercader** [comment]
Hi @barry1955, the `dataset_extent_map` was removed a long time ago in favour of just a template snippet that you add to your own templates, so you can remove it from `ckan.plugins`: 

http://docs.ckan.org/projects/ckanext-spatial/en/latest/spatial-search.html#dataset-extent-map

The `wms_preview` plugin is also deprecated in favour of `geo_view` so you can remove it as well.

Did you find these plugins in some old docs? Would be good to know so we can remove them

**Comment by barry1955** [comment]
Hi,
Thanks.

I'll try to find the reference I used.  I've removed the wms_preview as well.

I'll try to post a link to the docs I looked up, but I may well have been making it up as I went along.
