### ISSUE TITLE
Spatial search returning too many results

### ISSUE THREAD

**Issue by LondonAppDev** [ckan/ckanext-spatial#177]
I'm not sure if this is a bug or if I have done something wrong in the configuration.

I have a CKAN 2.6.2 instance with the latest version of `ckanext-spatial` (installed from the master branch). I am using the `solr` backend and have added the solr fields to the schema as suggested here: http://docs.ckan.org/projects/ckanext-spatial/en/latest/spatial-search.html. I am also using Solr 6.0.

Here is a URL to the instance:
http://rdds.researchdata.alpha.jisc.ac.uk

My problem is that when using the map search, it returns **all** datasets where the coordinates _overlap_ the searched area. 

I would expect it to return only the datasets with the entire bounding box of the dataset falls within the selected area on the map.

Is this the desired behaviour or is something wrong with my instance?

Thanks in advance,
Mark

**Comment by amercader** [comment]
@LondonAppDev see https://lists.okfn.org/pipermail/ckan-dev/2017-June/011008.html

**Comment by amercader** [comment]
If we can come up with the relevant parameter for "Contain-like" queries, we can include both and make the behaviour configurable of course.

**Comment by LondonAppDev** [comment]
Thanks @amercader. Now at least I know that it is not an issue with how I have set it up and that this is the correct behaviour. 

We are going to leave the default behaviour for now and plan to implement this functionality at a later date. If I can work the change into this extension as a configurable option then I'll make a PR. 

Cheers,
Mark

**Comment by amercader** [comment]
Fantastic, thanks @LondonAppDev
