### ISSUE TITLE
configuring CSW support

### ISSUE THREAD

**Issue by terchris** [ckan/ckanext-spatial#184]
I'm configuring CSW support and have a question related to the documentation.

I have installed http://docs.ckan.org/projects/ckanext-spatial/en/latest/install.html#install-postgis by just blindly following the instructions.

Now following Setup instructions on  http://docs.ckan.org/projects/ckanext-spatial/en/latest/csw.html

Step 2 I find a bit confusing:

>Create a database for pycsw. In theory you can use the same database that CKAN is using, but if >you want to keep them separated, use the following command to create a new one (we’ll use the >same default user though):

>sudo -u postgres createdb -O ckan_default pycsw -E utf-8
>It is strongly recommended that you install PostGIS in the pycsw databaset, so its spatial functions >are used. See the Install PostGIS and system packages section for details.

As a first time installer I have no opinion or preferences on what database to use. I just want it to work. Then later I can look into theories and options.

The first section says that I can do something in theory. And the next says that it is highly recommended to do something. 

**My question is : should I do the theory thing or will that stop the spatial functions ?**

**Comment by amercader** [comment]
hi @terchris. you can use the main CKAN database (the "theory thing"). As you already installed PostGIS on it the spatial functions are already available.
