### ISSUE TITLE
No ckan-pycsw command is available.

### ISSUE THREAD

**Issue by frafra** [ckan/ckanext-spatial#297]
> The spatial extension offers the ckan-pycsw command [...]
-- https://github.com/ckan/ckanext-spatial/blob/992b2753fc24d0abb12ced5cf5aaa3a853ca9ea4/doc/csw.rst

There is no such command.

**Comment by amercader** [comment]
This is not a `ckan` command, it's standalone script located in `bin`, as described in the "How it works" section.

```
cd /usr/lib/ckan/default/src/ckanext-spatial
python bin/ckan_pycsw.py --help
```

I haven't personally used this command in a long time so it would be good to see if it still works as expected

**Comment by frafra** [comment]
Yes, thank you, I was just pointing out that the documentation is outdated.
The script itself is broken. See #298 and #299.
